### ISSUE TITLE
java.lang.RuntimeExceptionPyRaisable: java.lang.RuntimeException: Class zemberek.morphology.TurkishMorphology not found

### ISSUE THREAD

**Issue by sumeyras** [ozturkberkay/Zemberek-Python-Examples#1]
Öncelikle merhaba
noisy_text_normalization.py ı için 
--TurkishMorphology = jp.JClass('zemberek.morphology.TurkishMorphology')   satırını  çalıştırdığımda 
**raise _RUNTIMEEXCEPTION.PYEXC("Class %s not found" % name)

java.lang.RuntimeExceptionPyRaisable: java.lang.RuntimeException: Class zemberek.morphology.TurkishMorphology not found**  hatasını alıyorum. Sorun neyden kaynaklanıyor anlayamadım yardımcı olabilir misiniz..

**Comment by ozturkberkay** [comment]
[Doğru environment variable ayarları](https://stackoverflow.com/a/26640589) ile [JDK 8](https://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html) kurulumu yapın. Bilgisayarınız 64-bit ise Python ve Java kurulumları da 64-bit olmalı. Zemberek'in son sürümünü ise [buradan ](https://drive.google.com/drive/folders/0B9TrB39LQKZWX1RSang3M1VkYjQ)indirin ve [doğru klasörün ](https://github.com/ozturkberkay/Zemberek-Python-Examples#installation)içine koyun. Bu koşullar altında kod sorunsuz çalışmaktadır.

![image](https://user-images.githubusercontent.com/7548962/61218537-e7b68e80-a71a-11e9-8527-e93e44854fca.png)

**Comment by Begummm** [comment]
Merhaba,

Bende ayni hatayi aliyorum. 
"TypeError: Class zemberek.morphology.TurkishMorphology is not found"
Ustelik sizin dediginiz sekilde JDK8 kurulumum var, Python ve Java kurulumlarim da 64 bit için. Zemberek icin dosyalamayida dediginiz gibi yaptim ancak hata veriyor. Baska bir sebep olabilir mi acaba?

![Capture](https://user-images.githubusercontent.com/46991070/95784956-1da74180-0cd5-11eb-816b-1274142dd1c4.PNG)

**Comment by BetulAktas** [comment]
Ben de aynı problemle karşılaştım, projedeki path'lerin tam halini yazınca sorun halloldu.

**Comment by BetulAktas** [comment]
> Merhaba,
> 
> Bende ayni hatayi aliyorum.
> "TypeError: Class zemberek.morphology.TurkishMorphology is not found"
> Ustelik sizin dediginiz sekilde JDK8 kurulumum var, Python ve Java kurulumlarim da 64 bit için. Zemberek icin dosyalamayida dediginiz gibi yaptim ancak hata veriyor. Baska bir sebep olabilir mi acaba?
> 
> ![Capture](https://user-images.githubusercontent.com/46991070/95784956-1da74180-0cd5-11eb-816b-1274142dd1c4.PNG)

Ben de aynı problemle karşılaştım, projedeki path'lerin tam halini yazınca sorun halloldu.

**Comment by estimatedgasfee** [comment]
> > Merhaba,
> > Bende ayni hatayi aliyorum.
> > "TypeError: Class zemberek.morphology.TurkishMorphology is not found"
> > Ustelik sizin dediginiz sekilde JDK8 kurulumum var, Python ve Java kurulumlarim da 64 bit için. Zemberek icin dosyalamayida dediginiz gibi yaptim ancak hata veriyor. Baska bir sebep olabilir mi acaba?
> > ![Capture](https://user-images.githubusercontent.com/46991070/95784956-1da74180-0cd5-11eb-816b-1274142dd1c4.PNG)
> 
> Ben de aynı problemle karşılaştım, projedeki path'lerin tam halini yazınca sorun halloldu.

merhabalar proje path'lerinin tam halini yazmaya ornek verebilir misiniz acaba ? 
tesekkurler.

**Comment by BetulAktas** [comment]
> > > Merhaba,
> > > Bende ayni hatayi aliyorum.
> > > "TypeError: Class zemberek.morphology.TurkishMorphology is not found"
> > > Ustelik sizin dediginiz sekilde JDK8 kurulumum var, Python ve Java kurulumlarim da 64 bit için. Zemberek icin dosyalamayida dediginiz gibi yaptim ancak hata veriyor. Baska bir sebep olabilir mi acaba?
> > > ![Capture](https://user-images.githubusercontent.com/46991070/95784956-1da74180-0cd5-11eb-816b-1274142dd1c4.PNG)
> > 
> > 
> > Ben de aynı problemle karşılaştım, projedeki path'lerin tam halini yazınca sorun halloldu.
> 
> merhabalar proje path'lerinin tam halini yazmaya ornek verebilir misiniz acaba ?
> tesekkurler.

Benim kullandığım kodlar farklıydı, kodlarda değişiklik yapılmış. Benim kullanığım kodlarda örneğin;
ZEMBEREK_PATH: str = join('..', '..', 'bin', 'zemberek-full.jar') gibi bir path vardı bunun yerine;
ZEMBEREK_PATH = 'C:/PythonCode/zemberek/bin/zemberek-full.jar' yazmıştım. Bütün path'leri bu şekilde düzeltince çalıştırabilmiştim ama şu anki kodlar farklı.

**Comment by ozturkberkay** [comment]
Merhaba,

Relative path verdiğiniz zaman, yani `join('..', '..', 'bin', 'zemberek-full.jar')` gibi, kodu çalıştırdığınız dizin, kodun bulunduğu dizin olmalı. Ancak kodları değiştirdim, tüm dizinler absolute formatta. Böyle bir şart yok artık. Yeni sürüm ile tekrar deneyebilirsiniz.

**Comment by denizerden** [comment]
Merhaba,

@ozturkberkay Aynı hatayı ben de alıyorum. Dediğiniz adımları uygulamama rapmen düzeltemedim. Java 8 mi olmak zorunda ben 11 kullanıyorum.
![image](https://user-images.githubusercontent.com/37370721/127643947-8b40d7b6-0a71-41cd-a233-df721c55a874.png)

**Comment by ozturkberkay** [comment]
Merhaba @denizerden,

`python -m downloader` komutunu çalıştırırsanız `zemberek-full.jar` dosyasını `bin` klasörü altına indirir. Ardından yazdığım kod JVM için `classpath` bilgisini bu jar dosyasının absolute konumu olarak tanımlar. Eğer jar dosyası bu konumda değil ise "not found" hatası alırsınız. `README.md` dosyasındaki komutları adım adım takip ederseniz doğru şekilde kurabilirsiniz. Başka kurulumlar için `classpath` ve `jvmpath` gibi ayarları sizin yönetmeniz lazım. Gördüğünüz gibi sıfırdan yaptığım Java 11 kurulumu ile çalışıyor:

```terminal
(.env) C:\Users\berkayozturk\Desktop\Zemberek-Python-Examples>echo %JAVA_HOME%
C:\Program Files\Java11

(.env) C:\Users\berkayozturk\Desktop\Zemberek-Python-Examples>python -m main morphology.stem_and_lemmatize "Yazılımcı"
I|10:31:54.422|Root lexicon created in 383 ms.                                                                     | DictionarySerializer#getDictionaryItems
I|10:31:54.424|Dictionary generated in 429 ms                                                                      | RootLexicon#defaultBinaryLexicon
I|10:31:54.792|Initialized in 804 ms.                                                                              | TurkishMorphology#createWithDefaults

    Stemming and lemmatization example.

    Args:
        word (str): Word to apply stemming and lemmatization.

I|10:31:55.059|Initialized in 200 ms.                                                                              | TurkishMorphology#createWithDefaults

Results:
[yazılım:Noun] yazılım:Noun+A3sg|cı:Agt→Noun+A3sg
        Stems = yazılım, yazılımcı
        Lemmas = yazılım, yazılımcı
```

Başka bir dosya konumundan Jupyter notebook ile Zemberek çalıştırmak istiyorsanız aşağıdaki gibi kendiniz JVM çalıştırın:

```python
startJVM(jvmpath=getDefaultJVMPath(), classpath='ZEMBEREK PATH', convertStrings=False, interrupt=True)
```
