### ISSUE TITLE
Jpype1 Installation problem

### ISSUE THREAD

**Issue by barisegesevgili** [ozturkberkay/Zemberek-Python-Examples#2]
I have faced with a problem when installing JPype1 to my Mac (where pip&pip3 exists) with the following command:

- pip install JPype1

Instead I tried to install the package with 

- pip3 install JPype1

and it worked for me.

FYI

**Comment by barisegesevgili** [comment]
IMO, the reason of the problem is that I have earlier versions of python installed on my pc (2.7)

**Comment by ozturkberkay** [comment]
> IMO, the reason of the problem is that I have earlier versions of python installed on my pc (2.7)

`pip` is just a soft-link to the executable. AFAIK, if you installed Python version 2.x before installing version 3.x, you will have two separate links. 

You can just check that using:
`pip show pip`
